version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: example/demo:v1
    ports:
      - "8090:8090"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
